<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Experimental design and statistical methods - 5&nbsp; Complete factorial designs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-blocking_ancova.html" rel="next">
<link href="./04-contrasts_multipletesting.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-interactions_multiway.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Complete factorial designs</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Experimental design and statistical methods</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/lbelzile/math80667a/" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./MATH80667A-EDSM.pdf" rel="" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-hypothesis_testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-completely_randomized_trials.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Completely randomized designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-contrasts_multipletesting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Contrasts and multiple testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-interactions_multiway.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Complete factorial designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-blocking_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Designs to reduce the error</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-power_effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Effect sizes and power</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-reproducibility_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Replication crisis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-repeated.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Repeated measures and multivariate models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Introduction to mixed models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-causal-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Causal inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Nonparametric tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#efficiency-of-multiway-analysis-of-variance." id="toc-efficiency-of-multiway-analysis-of-variance." class="nav-link active" data-scroll-target="#efficiency-of-multiway-analysis-of-variance."><span class="header-section-number">5.1</span> Efficiency of multiway analysis of variance.</a></li>
  <li><a href="#interactions" id="toc-interactions" class="nav-link" data-scroll-target="#interactions"><span class="header-section-number">5.2</span> Interactions</a></li>
  <li><a href="#model-parametrization" id="toc-model-parametrization" class="nav-link" data-scroll-target="#model-parametrization"><span class="header-section-number">5.3</span> Model parametrization</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/lbelzile/math80667a/edit/main/05-interactions_multiway.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header">
<h1 class="title display-7"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Complete factorial designs</span></h1>

</header>

<p>We next consider experiments and designs in which there are multiple factors being manipulated by the experimenter simultaneously. Before jumping into the statistical analysis, let us discuss briefly some examples that will be covered in the sequel.</p>
<div id="exm-STC21" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.1 (Psychological ownership of borrowed money) </strong></span>Supplemental Study 5 from <span class="citation" data-cites="Sharma.Tully.Cryder:2021">Sharma, Tully, and Cryder (<a href="references.html#ref-Sharma.Tully.Cryder:2021" role="doc-biblioref">2021</a>)</span> checks the psychological perception of borrowing money depending on the label. The authors conducted a 2 by 2 between-subject comparison (two-way ANOVA) varying the type of debt (whether the money was advertised as credit or loan) and the type of purchase the latter would be used for (discretionary spending or need). The response is the average of the likelihood and interest in the product, both measured using a 9 point Likert scale from 1 to 9.</p>
</div>
<div id="exm-MP14" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.2 (Spatial orientation shrinks and expands psychological distance) </strong></span><span class="citation" data-cites="Maglio.Polman:2014">Maglio and Polman (<a href="references.html#ref-Maglio.Polman:2014" role="doc-biblioref">2014</a>)</span> measured the subjective distance on travel based on the direction of travel. They conducted an experiment in the Toronto subway green line, asking commuters from Bay station to answer the question “How far away does the [name] station feel to you?” using a 7 point Likert scale ranging from very close (1) to very far (7). The stations name were one of Spadina, St.&nbsp;George, Bloor–Yonge and Sherbourne (from West to East).</p>
<p>As there are four stations and two directions of travel (a 4 by 2 design), the scientific question of interest for subjective measures of distance would consist of perceiving differently the distance depending on the direction of travel. We could also wonder whether destinations that are two stations away from Bay (Spadina and Sherbourne) would be considered equidistant, and similarly for the other two.</p>
</div>
<section id="efficiency-of-multiway-analysis-of-variance." class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="efficiency-of-multiway-analysis-of-variance."><span class="header-section-number">5.1</span> Efficiency of multiway analysis of variance.</h2>
<p>Consider the setting of <span class="citation" data-cites="Sharma.Tully.Cryder:2021">Sharma, Tully, and Cryder (<a href="references.html#ref-Sharma.Tully.Cryder:2021" role="doc-biblioref">2021</a>)</span> and suppose we want to check the impact of debt and collect a certain number of observations in each group. If we suspected the label had an influence, we could run a one-way analysis of variance for each spending type separately (thus, two one-way ANOVA each with two groups). We could do likewise if we wanted instead to focus on whether the spending was discretionary in nature or not, for each label: together, this would give a total of eight sets of observations. Combining the two factors allows us to halve the number of groups/samples we collect in this simple setting: this highlights the efficiency of running an experiment modifying all of these instances at once, over a series of one-way analysis of variance. This concept extends to higher dimension when we manipulate two or more factors. Factorial designs allow us to study the impact of multiple variables simultaneously with <strong>fewer overall observations</strong>.</p>
<p>The drawback is that as we increase the number of factors, the total number of subgroups increases: with a complete design<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> and with factors <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, <span class="math inline">\(C\)</span>, etc. with <span class="math inline">\(n_a\)</span>, <span class="math inline">\(n_b\)</span>, <span class="math inline">\(n_c\)</span>, <span class="math inline">\(\ldots\)</span> levels, we have a total of <span class="math inline">\(n_a\times n_b \times n_c \times \cdots\)</span> combinations and the number of observations needed to efficiently measure the group means increases quickly. This is the <strong>curse of dimensionality</strong>: the larger the number of experimental treatments manipulated together, the larger the sample size needed. A more efficient approach, which we will cover in later section, relies on measuring multiple observations from the same experimental units, for example by giving multiple tasks (randomly ordered) to participants.</p>
<p>Intrinsically, the multiway factorial design model description does not change relative to a one-way design: the analysis of variance describes the sample mean for the response in each subgroup,</p>
<p>Consider a two-way analysis of variance model. This is a linear model with two factors, <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, with respectively <span class="math inline">\(n_a\)</span> and <span class="math inline">\(n_b\)</span> levels. The response <span class="math inline">\(Y_{ijk}\)</span> of the <span class="math inline">\(k\)</span>th measurement in group <span class="math inline">\((a_i, b_j)\)</span> is <span id="eq-twowayasoneway"><span class="math display">\[
\underset{\text{response}\vphantom{b}}{Y_{ijk}} = \underset{\text{subgroup mean}}{\mu_{ij}} + \underset{\text{error term}}{\varepsilon_{ijk}}
\tag{5.1}\]</span></span> where</p>
<ul>
<li><span class="math inline">\(Y_{ijk}\)</span> is the <span class="math inline">\(k\)</span>th replicate for <span class="math inline">\(i\)</span>th level of factor <span class="math inline">\(A\)</span> and <span class="math inline">\(j\)</span>th level of factor <span class="math inline">\(B\)</span></li>
<li><span class="math inline">\(\mu_{ij}\)</span> is the average response of measurements in group <span class="math inline">\((a_i, b_j)\)</span></li>
<li><span class="math inline">\(\varepsilon_{ijk}\)</span> are independent error terms with mean zero and standard deviation <span class="math inline">\(\sigma\)</span>.</li>
</ul>
<p>This, it turns out, is a special case of linear regression model. We could build contrasts for comparing group averages, but it will more convenient to reparametrize the model so that hypotheses of interest are directly expressed in terms of the parameters.</p>
<p>For example, in the <span class="citation" data-cites="Maglio.Polman:2014">Maglio and Polman (<a href="references.html#ref-Maglio.Polman:2014" role="doc-biblioref">2014</a>)</span> study, we could gather observations for each factor combination in a table, where <code>direction</code> is the row and <code>station</code> the column.</p>
<div id="tbl-cellmeansMP14" class="anchored">
<table class="table">
<caption>Table&nbsp;5.1: Conceptual depiction of cell average for the two by two design of <span class="citation" data-cites="Maglio.Polman:2014">Maglio and Polman (<a href="references.html#ref-Maglio.Polman:2014" role="doc-biblioref">2014</a>)</span></caption>
<colgroup>
<col style="width: 30%">
<col style="width: 2%">
<col style="width: 30%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(A\)</span> <code>station</code></th>
<th><span class="math inline">\(B\)</span> <code>direction</code></th>
<th style="text-align: center;"><span class="math inline">\(b_1\)</span> (<code>east</code>)</th>
<th style="text-align: center;"><span class="math inline">\(b_2\)</span> (<code>west</code>)</th>
<th style="text-align: center;">row mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(a_1\)</span> (<code>Spadina</code>)</td>
<td></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{11}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{12}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{1.}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(a_2\)</span> (<code>St. George</code>)</td>
<td></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{21}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{22}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{2.}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(a_3\)</span> (<code>Bloor-Yonge</code>)</td>
<td></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{31}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{32}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{3.}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(a_4\)</span> (<code>Sherbourne</code>)</td>
<td></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{41}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{42}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{4.}\)</span></td>
</tr>
<tr class="odd">
<td>column mean</td>
<td></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{.1}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{.2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>The <span class="math inline">\(i\)</span>th row mean represents the average response across all levels of <span class="math inline">\(B\)</span>, <span class="math inline">\(\mu_{i.} = (\mu_{i1} + \cdots + \mu_{in_b})/n_b\)</span> and similarly for the average of the <span class="math inline">\(j\)</span>th column, <span class="math inline">\(\mu_{.j} = (\mu_{1j} + \cdots + \mu_{n_aj})/n_a.\)</span> Finally, the overall average is <span class="math display">\[\mu = \frac{\sum_{i=1}^{n_a} \sum_{j=1}^{n_b} \mu_{ij}}{n_an_b}.\]</span></p>
<p>Each subgroup average <span class="math inline">\(\mu_{ij}\)</span> will be estimated as the sample mean of observations in their group and we would use the above formulae to obtain estimates of the row, column and overall means <span class="math inline">\(\widehat{\mu}_{i.}\)</span>, <span class="math inline">\(\widehat{\mu}_{.j}\)</span> and <span class="math inline">\(\widehat{\mu}\)</span>. If the sample is balanced, meaning the number of observations is the same, these will be the same as summing over all observations in a row, column or table and then averaging. In general setup, however, we will give equal weight to each subgroup average.</p>
<div class="cell" data-hash="05-interactions_multiway_cache/html/tbl-balance-MP14_3bbe46c32639693e57530e9ceec5e4d2">
<div class="cell-output-display">
<div id="tbl-balance-MP14" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;5.2: Repartition of the sample for Study 1 of Maglio and Polman (2014).</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Spadina</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">St. George</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Bloor-Yonge</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sherbourne</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">east</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="even">
<td style="text-align: left;">west</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">25</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Looking at <a href="#tbl-balance-MP14">Table&nbsp;<span>5.2</span></a>, we can see that the number of observations is not exactly the same. In general, attrition and non-response can lead to unequal cell sample size, but you should strive to gather roughly equal number of observations. The main consequence is that different decompositions of the variance will lead to different tests, whereas no such ambiguity exists for balanced data.</p>
</section>
<section id="interactions" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="interactions"><span class="header-section-number">5.2</span> Interactions</h2>
<p><a href="#tbl-cellmeansMP14">Table&nbsp;<span>5.1</span></a> shows the individual mean of each subgroup. From these, we may be interested in looking at the experiment as a single one-way analysis of variance model with eight subgroups, or as a series of one-way analysis of variance with either <code>direction</code> or <code>station</code> as sole factor.</p>
<p>We will use particular terminology to refer to these:</p>
<ul>
<li><strong>simple effects</strong>: difference between levels of one in a fixed combination of others. Simple effects are comparing cell averages within a given row or column.</li>
<li><strong>main effects</strong>: differences relative to average for each condition of a factor. Main effects are row/column averages.</li>
<li><strong>interaction effects</strong>: when simple effects differ depending on levels of another factor. Interactions effects are differences relative to the row or column average.</li>
</ul>
<p>In other words, an interaction occurs when some experimental factors, when coupled together, have different impacts than the superposition of each. An interaction between two factors occurs when the average effect of one independent variable depends on the level of the other.</p>
<p>If there is a significant interaction, the main effects are <strong>not</strong> of interest since they are misleading. Rather, we will compute the simple effects by making the comparison one at level at the time.</p>
<p>In our example of <span class="citation" data-cites="Maglio.Polman:2014">Maglio and Polman (<a href="references.html#ref-Maglio.Polman:2014" role="doc-biblioref">2014</a>)</span>, a simple effect would be comparing the distance between Spadina and Sherbourne for east. The main effect for the direction would be the average perceived distance for east and for west. Finally, the interaction would measure how much these differ by station depending on direction.</p>
<div class="cell" data-hash="05-interactions_multiway_cache/html/fig-2by2_ba833c96d680042b22cd0bf8b906ae45">
<div class="cell-output-display">
<div id="fig-2by2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-interactions_multiway_files/figure-html/fig-2by2-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.1: Interaction plots (line graphs) for example patterns for means for each of the possible kinds of general outcomes in a 2 by 2 design. Illustration adapted from Figure 10.2 of <span class="citation" data-cites="Crump.Navarro.Suzuki:2019">Crump, Navarro, and Suzuki (<a href="references.html#ref-Crump.Navarro.Suzuki:2019" role="doc-biblioref">2019</a>)</span> by Matthew Crump (CC BY-SA 4.0 license).</figcaption>
</figure>
</div>
</div>
</div>
<p>To better understand, we consider the average response and suppose we have access to the true population average for each sub-treatment. We can then represent the population using a line graph with the two factors, one being mapped to color and another to the <span class="math inline">\(x\)</span>-axis. <a href="#fig-2by2">Figure&nbsp;<span>5.1</span></a> shows what happens under all possible scenarios with a 2 by 2 design. When there is no overall effect, the mean is constant. If there isn’t a main effect of <span class="math inline">\(A\)</span>, the average of the two mean response for <span class="math inline">\(a_1\)</span> and <span class="math inline">\(a_2\)</span> are the same, etc. Interactions are depicted by <strong>non-parallel lines</strong>.</p>
<p>It’s clear from <a href="#fig-2by2">Figure&nbsp;<span>5.1</span></a> that looking only at the average of <span class="math inline">\(A\)</span> alone (the main effect) isn’t instructive when we are in the presence of an interaction: rather, we should be comparing the values of <span class="math inline">\(A\)</span> for <span class="math inline">\(b_1\)</span> separately than those for <span class="math inline">\(b_2\)</span>, and vice-versa, using simple effects, otherwise our conclusions may be misleading.</p>
<div id="exm-MP14-interaction" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.3 (Interaction plots for Maglio and Polman (2014)) </strong></span>The hypothesis of interest is the interaction; for the time being, we can simply plot the average per group. Since the summary statistics can hide important information such as the uncertainty, we add 95% confidence intervals for the subgroup averages and superimpose jittered observations to show the spread of the data. Based on <a href="#fig-interactionplotMP">Figure&nbsp;<span>5.2</span></a>, there appears to be at least an interaction between station and direction of travel, in addition to a main effect for station. Formal hypothesis testing can help check this intuition.</p>
<div class="cell" data-hash="05-interactions_multiway_cache/html/fig-interactionplotMP_38bd5c332fb9984ad8fc5cb4587b5dcd">
<div class="cell-output-display">
<div id="fig-interactionplotMP" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-interactions_multiway_files/figure-html/fig-interactionplotMP-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;5.2: Interaction plot for Study 1 of <span class="citation" data-cites="Maglio.Polman:2014">Maglio and Polman (<a href="references.html#ref-Maglio.Polman:2014" role="doc-biblioref">2014</a>)</span>, showing group averages and 95% confidence intervals for the means. Observations are overlaid on the graph.</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="model-parametrization" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="model-parametrization"><span class="header-section-number">5.3</span> Model parametrization</h2>
<p>The following section is technical and may be omitted.</p>
<p>The model parametrized in terms of subgroup or cell average is okay in <a href="#eq-twowayasoneway">Equation&nbsp;<span>5.1</span></a>, but it doesn’t help us if we want to check for the presence of main effects and interaction, even if it would be possible to specify the contrasts required to test these hypotheses. We can however express the model in terms of main effects and interactions.</p>
<p>We consider the alternative formulation <span class="math display">\[\begin{align*}
Y_{ijk} = \mu + \alpha_i + \beta_j + (\alpha\beta)_{ij} + \varepsilon_{ijk},
\end{align*}\]</span> where</p>
<ul>
<li><span class="math inline">\(\mu\)</span> is the average of all subgroup averages, termed overall mean.</li>
<li><span class="math inline">\(\alpha_i = \mu_{i.} - \mu\)</span> is the mean of level <span class="math inline">\(A_i\)</span> minus the overall mean.</li>
<li><span class="math inline">\(\beta_j = \mu_{.j} - \mu\)</span> is the mean of level <span class="math inline">\(B_j\)</span> minus overall mean.</li>
<li><span class="math inline">\((\alpha\beta)_{ij} = \mu_{ij} - \mu_{i.} - \mu_{.j} + \mu\)</span> is the interaction term for <span class="math inline">\(A_i\)</span> and <span class="math inline">\(B_j\)</span> which encodes the effect of both variable not already captured by the main effects.</li>
</ul>
<p>A rapid calculation shows that there are more coefficients than the number of cells and subgroups (<span class="math inline">\(n_an_b\)</span> cells overall) in our table. The model is <strong>overparametrized</strong>: to get away with this, we impose constraints to remove redundancies. The idea is that if we know <span class="math inline">\(n_a-1\)</span> of the mean for factor <span class="math inline">\(A\)</span> and the global average is a combination of these, we can deduce the value for the last row mean. The model formulation in terms of difference from the global average or main effect ensures that we can test for main effects for factor <span class="math inline">\(A\)</span> by setting <span class="math inline">\(\mathscr{H}_0: \alpha_1 = \cdots = \alpha_{n_a-1}=0\)</span>. The <span class="math inline">\(1 + n_a + n_b\)</span> <strong>sum to zero</strong> constraints, <span class="math display">\[\sum_{i=1}^{n_a} \alpha_i=0, \quad \sum_{j=1}^{n_b} \beta_j=0, \quad  \sum_{j=1}^{n_b} (\alpha\beta)_{ij}=0, \quad \sum_{i=1}^{n_a} (\alpha\beta)_{ij}=0,\]</span> restore identifiability.</p>
<p>The redundancy in information, due to the fact main effects are expressible as row and column averages, and the overall mean as the average of all observations, will arise again when we consider degrees of freedom for tests.</p>
<p><strong>To be continued</strong>…</p>
<div id="exm-borrowed-money-test" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.4 (Testing for Psychological ownership of borrowed money) </strong></span><span class="citation" data-cites="Sharma.Tully.Cryder:2021">Sharma, Tully, and Cryder (<a href="references.html#ref-Sharma.Tully.Cryder:2021" role="doc-biblioref">2021</a>)</span> first proceeded with the test for the interaction. Since there are one global average and two main effect (additional difference in average for both factors <code>debttype</code> and <code>purchase</code>), the interaction involves one degree of freedom since we go from a model with three parameters describing the mean to one that has a different average for each of the four subgroups.</p>
<p>The reason why this is first test to carry out is that if the effect of one factor depends on the level of the other, as shown in <a href="#fig-2by2">Figure&nbsp;<span>5.1</span></a>, then we need to compare the label of debt type separately for each type of purchase and vice-versa using simple effects. If the interaction on the contrary isn’t significant, then we could pool observations instead and average across either of the two factors, resulting in the marginal comparisons with the main effects.</p>
<p>Fitting the model including the interaction between factors ensures that we keep the additivity assumption and that our conclusions aren’t misleading: the price to pay is additional mean parameters to be estimated, which isn’t an issue if you collect enough data, but can be critical when data collection is extremely costly and only a few runs are allowed.</p>
<p>In <strong>R</strong>, we include both factors in a formula as <code>response ~ factorA * factorB</code>, the <code>*</code> symbol indicating that both are allowed to interact; in the main effect model, we would use instead <code>+</code> to reflect that the effects of both factors add up.</p>
<div class="cell" data-hash="05-interactions_multiway_cache/html/unnamed-chunk-5_e07f0b8623131619809363a2ef794e5b">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Analysing Supplementary Study 5</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># of Sharma, Tully, and Cryder (2021)</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(STC21_SS5, <span class="at">package =</span> <span class="st">"hecedsm"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">aov</span>(likelihood <span class="sc">~</span> purchase<span class="sc">*</span>debttype, </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> STC21_SS5)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">model.tables</span>(mod, <span class="at">type =</span> <span class="st">"means"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Tables of means
Grand mean
         
4.879747 

 purchase 
    discretionary    need
            4.182   5.579
rep       751.000 750.000

 debttype 
     credit    loan
      5.127   4.631
rep 753.000 748.000

 purchase:debttype 
               debttype
purchase        credit loan 
  discretionary   4.5    3.8
  rep           392.0  359.0
  need            5.7    5.4
  rep           361.0  389.0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Analysis of variance reveals </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># non-significant interaction</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># of purchase and type</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(mod, <span class="at">type =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: likelihood
                   Sum Sq   Df   F value    Pr(&gt;F)    
(Intercept)        7974.0    1 1040.9610 &lt; 2.2e-16 ***
purchase            282.8    1   36.9137 1.563e-09 ***
debttype             88.5    1   11.5483 0.0006959 ***
purchase:debttype    13.7    1    1.7852 0.1817132    
Residuals         11467.4 1497                        
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Main effects</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>emmeans<span class="sc">::</span><span class="fu">emmeans</span>(mod, </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">specs =</span> <span class="st">"debttype"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">contr =</span> <span class="st">"pairwise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: Results may be misleading due to involvement in interactions</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 debttype emmean    SE   df lower.CL upper.CL
 credit     5.12 0.101 1497     4.93     5.32
 loan       4.63 0.101 1497     4.43     4.83

Results are averaged over the levels of: purchase 
Confidence level used: 0.95 

$contrasts
 contrast      estimate    SE   df t.ratio p.value
 credit - loan    0.496 0.143 1497   3.469  0.0005

Results are averaged over the levels of: purchase </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise comparisons within levels of purchase</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple effect</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>emmeans<span class="sc">::</span><span class="fu">emmeans</span>(mod, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">specs =</span> <span class="fu">c</span>(<span class="st">"purchase"</span>, <span class="st">"debttype"</span>),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">by =</span> <span class="st">"purchase"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">contr =</span> <span class="st">"pairwise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
purchase = discretionary:
 debttype emmean    SE   df lower.CL upper.CL
 credit     4.51 0.140 1497     4.24     4.78
 loan       3.82 0.146 1497     3.54     4.11

purchase = need:
 debttype emmean    SE   df lower.CL upper.CL
 credit     5.74 0.146 1497     5.45     6.02
 loan       5.43 0.140 1497     5.16     5.71

Confidence level used: 0.95 

$contrasts
purchase = discretionary:
 contrast      estimate    SE   df t.ratio p.value
 credit - loan    0.687 0.202 1497   3.398  0.0007

purchase = need:
 contrast      estimate    SE   df t.ratio p.value
 credit - loan    0.305 0.202 1497   1.508  0.1318</code></pre>
</div>
</div>
<p>In the analysis of variance table, we focus exclusively on the last line with the sum of squares for <code>purchase:debttype</code>. The <span class="math inline">\(F\)</span> statistic is 1.79; using the <span class="math inline">\(\mathsf{F}\)</span> (1, 1497) distribution as benchmark, we obtain a <span class="math inline">\(p\)</span>-value of 0.18 so there is no evidence the effect of purchase depends on debt type.</p>
<p>We can thus pool data and look at the effect of debt type (<code>loan</code> or <code>credit</code>) overall by combining the results for all purchase types, one of the planned comparison reported in the Supplementary material. To do this in <strong>R</strong> with the <code>emmeans</code> package, we use the <code>emmeans</code> function and we quote the factor of interest (i.e., the one we want to keep) in <code>specs</code>. By default, this will compute the estimate marginal means: the <code>contr = "pairwise"</code> indicates that we want the difference between the two, which gives us the contrasts.</p>
<p>To get the simple effects, we give both variables in <code>specs</code> as factors for which to compute subgroup means, then set additionally the <code>by</code> command to specify which variable we want separate results for. We get the difference in average between <code>credit</code> and <code>loan</code> labels for each purchase type along with the <span class="math inline">\(t\)</span> statistics for the marginal contrast and the <span class="math inline">\(p\)</span>-value. The simple effects suggest that the label has an impact on perception only for discretionary expenses rather than needed ones, which runs counter-intuitively with the lack of interaction.</p>
</div>
<div class="example" name="Spatial perception of distance in the Toronto subway">
<p><span class="citation" data-cites="Maglio.Polman:2014">Maglio and Polman (<a href="references.html#ref-Maglio.Polman:2014" role="doc-biblioref">2014</a>)</span> considered the relative perception of distance from Bay station in Toronto. We modify the data so that we consider station distance in direction of travel (rather than station names). The categorical variable <code>stdist</code> has labels <span class="math inline">\((-2, -1, +1, +2\)</span>) for stations Spadina, St.&nbsp;Georges, Bloor-Yonge, Sherbourne in direction East, and opposite signs in the other direction: see <a href="#fig-Torontosubway">Figure&nbsp;<span>5.3</span></a> for the map. We are interested in knowing whether two stations behind (<code>stdist</code><span class="math inline">\(=-2\)</span>) is perceived the same as two stations ahead (<code>stdist</code><span class="math inline">\(=+2\)</span>).</p>
<div class="cell" data-hash="05-interactions_multiway_cache/html/fig-Torontosubway_fb8d6af10e41dfd21f2f534a1fcfa0a0">
<div class="cell-output-display">
<div id="fig-Torontosubway" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/Toronto_subway.png" class="img-fluid figure-img" width="494"></p>
<figcaption class="figure-caption">Figure&nbsp;5.3: Simplified depiction of the Toronto metro stations used in the experiment, based on work by Craftwerker on Wikipedia, distributed under CC-BY-SA 4.0.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-hash="05-interactions_multiway_cache/html/unnamed-chunk-8_ac956b022d8e59cf26202c63d3a6dd4b">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up parametrization to sum-to-zero for categorical factors</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">c</span>(<span class="st">"contr.sum"</span>, <span class="st">"contr.poly"</span>))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(distance <span class="sc">~</span> stdist <span class="sc">*</span> direction, <span class="at">data =</span> MP14_S1) </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(mod, <span class="at">type =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="05-interactions_multiway_cache/html/tbl-ANOVA2-MP14_0cba122b0d01b1429a29ab42221eb9e0">
<div class="cell-output-display">
<div id="tbl-ANOVA2-MP14" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;5.3: Analysis of variance (type II effects) for the Maglio and Polman (2014) reformated data.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sum of squares</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">stat</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">stdist</td>
<td style="text-align: right;">121.87</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.86</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">direction</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: left;">0.55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">stdist:direction</td>
<td style="text-align: right;">5.70</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1.77</td>
<td style="text-align: left;">0.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">208.15</td>
<td style="text-align: right;">194</td>
<td style="text-align: right;"></td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>We look at the analysis of variance in <a href="#tbl-ANOVA2-MP14">Table&nbsp;<span>5.3</span></a> to see what the perception of distance is. The <span class="math inline">\(F\)</span>-tests suggest that there is no interaction, and no effect of direction of travel although there is an uninteresting main effect of station distance (of course, two station apart is considered further from Bay than one station apart).</p>
<p>Since there is no interaction, we can collapse the data to a one-way ANOVA with a single factor (station distance) and consider contrasts. Say we are interested in testing the perception of distance, by looking at average distance of pairs at equal distance <span class="math inline">\(\mu_{-1} = \mu_{+1}\)</span> and <span class="math inline">\(\mu_{-2} = \mu_{+2}\)</span>.</p>
<div class="cell" data-hash="05-interactions_multiway_cache/html/fig-interactionMP_fcaa85a6874455a61c6f70a5062dc348">
<div class="cell-output-display">
<div id="fig-interactionMP" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-interactions_multiway_files/figure-html/fig-interactionMP-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;5.4: Interaction plot for the reformated data from Maglio and Polman (2014) with 95% confidence intervals.</figcaption>
</figure>
</div>
</div>
</div>
<p>If we have categories are in the order <span class="math inline">\((-2, -1, +1, +2)\)</span>, the contrast weights are <span class="math inline">\((-1, 0, 0, 1)\)</span> and <span class="math inline">\((0, -1, 1, 0)\)</span> or a multiple thereof; the two contrasts are orthogonal. <a href="#tbl-contrast-MP14">Table&nbsp;<span>5.4</span></a> shows the result of the hypothesis tests: both are significant, even applying a Bonferroni correction. This supports the hypothesis of <span class="citation" data-cites="Maglio.Polman:2014">Maglio and Polman (<a href="references.html#ref-Maglio.Polman:2014" role="doc-biblioref">2014</a>)</span>.</p>
<div class="cell" data-hash="05-interactions_multiway_cache/html/tbl-contrast-MP14_62fb477fb157e3a73c9eb5a2c086544b">
<div class="cell-output-display">
<div id="tbl-contrast-MP14" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;5.4: Contrasts for comparing the perceived distance for stations at the same distance on the network, but in opposition directions to that of travel.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">contrast</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std. error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">stat</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">two dist</td>
<td style="text-align: right;">-1.12</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">-5.47</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">one dist</td>
<td style="text-align: right;">-0.86</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">-4.13</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</div>
<p>It is important to understand that any multiway ANOVA with two or more factor can be collapsed into a single one-way ANOVA: this is notably useful when there is a control group which is not related to the factor levels, as no manipulation takes place. The use of contrasts becomes critical since we can write any test for main effects, interactions using the latter through weighting.</p>
<div id="exm-LKUK24" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.5 (Perceptions of cultural appropriation by ideology) </strong></span>We consider a three-way ANOVA from <span class="citation" data-cites="Lin.Kim.Uduehi.Keinan:2024">Lin et al. (<a href="references.html#ref-Lin.Kim.Uduehi.Keinan:2024" role="doc-biblioref">2024</a>)</span>. Their Study 4 focused on cultural appropriation for soul food recipe cookbook from Chef Dax, who was either black (or not), manipulating the description of the way he obtained the recipes (by peeking without permission in kitchens, by asking permission or no mention for control). Authors postulated that the perception of appropriation would vary by political ideology (liberal or conservative). The study results in a 3 by 2 by 2 three-way between-subject ANOVA.</p>
<p>For the <span class="math inline">\(K\)</span>-way ANOVA, we always start with estimating the full model with all <span class="math inline">\(K\)</span>-way interaction (provided there are enough data to estimate the latter, which implies there are repetitions). If the latter is significant, we can fix one or more factor levels and compare the others.</p>
<div class="cell" data-hash="05-interactions_multiway_cache/html/tbl-anova-LKUK24_6613bc2564d257d8b7b5a70993d76292">
<div class="cell-output-display">
<div id="tbl-anova-LKUK24" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;5.5: Analysis of variance table (type II decomposition) for the data from Study 4 of Lin et al. (2024).</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sum of squares</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">stat</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">politideo</td>
<td style="text-align: right;">48.49</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">21.35</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">chefdax</td>
<td style="text-align: right;">473.72</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">208.61</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">brandaction</td>
<td style="text-align: right;">34.24</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">7.54</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">politideo:chefdax</td>
<td style="text-align: right;">65.00</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">28.63</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">politideo:brandaction</td>
<td style="text-align: right;">1.56</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: left;">0.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">chefdax:brandaction</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: left;">0.87</td>
</tr>
<tr class="odd">
<td style="text-align: left;">politideo:chefdax:brandaction</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: left;">0.86</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">1587.33</td>
<td style="text-align: right;">699</td>
<td style="text-align: right;"></td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>If we consider <a href="#tbl-anova-LKUK24">Table&nbsp;<span>5.5</span></a>, we find that there is no three-way interaction and, omitting the latter and focusing on lower-level, a single two-way interaction between political ideology and the race of Chef Dax. We cannot interpret the <span class="math inline">\(p\)</span>-value for the main effect of <code>brandaction</code>, but we could look at the marginal means.</p>
<p>Based on the data, we will collapse data to a one-way ANOVA comparing the three levels of <code>brandaction</code> and a 2 by 2 two-way ANOVA for the other two factors. The results are obtained by averaging over the missing factor.</p>
<p>We are interested in comparing the perception between the race of Chef Dax (black or not, as Southern Soul food cooking is more likely to be associated with cultural appropriation is Chef Dax is not black. We proceed with <code>emmeans</code> by computing the marginal means separately for each of the four subcategories, but compare the race of Chef Dax separately for liberals and conservatives due to the presence of the interaction.</p>
<div class="cell" data-hash="05-interactions_multiway_cache/html/unnamed-chunk-14_8a897fe206772acdccfeb5050e6662f2">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(LKUK24_S4, <span class="at">package =</span> <span class="st">"hecedsm"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(appropriation <span class="sc">~</span> politideo <span class="sc">*</span> chefdax <span class="sc">*</span> brandaction,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> LKUK24_S4)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Marginal means for political ideology/Chef Dax</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>emm_racebypolit <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod, <span class="at">specs =</span> <span class="st">"chefdax"</span>, <span class="at">by =</span> <span class="st">"politideo"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>emm_racebypolit <span class="sc">|&gt;</span> <span class="fu">pairs</span>() <span class="co">#shortcut for contrast("pairwise")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>politideo = conservative:
 contrast          estimate    SE  df t.ratio p.value
 not black - black     0.71 0.206 699   3.438  0.0006

politideo = liberal:
 contrast          estimate    SE  df t.ratio p.value
 not black - black     2.03 0.135 699  14.998  &lt;.0001

Results are averaged over the levels of: brandaction </code></pre>
</div>
</div>
<p>We see that the liberals are much more likely to view Chef Dax cookbook as an instance of cultural appropriation if he is not black; there is limited evidence of any difference between conservatives and liberal when Chef Dax is black. Both differences are statistically significative, but the differences (and thus evidence of an effect) is much stronger for left-leaning respondents.</p>
<p>We can look next at the brand action: we expect participants will view peeking less favorably than if Chef Dax asked for permission to publish the recipes. It’s tricky to know the effect of the control, as we are not bringing the point to the attention of participants in this instance.</p>
<div class="cell" data-hash="05-interactions_multiway_cache/html/unnamed-chunk-15_22725ca1cb7b43dad43af4ba259cb65b">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Marginal mean for brandaction</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>emm_brand <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod, <span class="at">specs =</span> <span class="fu">c</span>(<span class="st">"brandaction"</span>)) </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>emm_brand</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> brandaction emmean    SE  df lower.CL upper.CL
 peeking       2.56 0.108 699     2.35     2.77
 permission    2.29 0.105 699     2.09     2.50
 control       2.07 0.108 699     1.86     2.28

Results are averaged over the levels of: politideo, chefdax 
Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Joint test for the main effect of brandaction</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>emm_brand <span class="sc">|&gt;</span> <span class="fu">pairs</span>() <span class="sc">|&gt;</span> <span class="fu">joint_tests</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> model term df1 df2 F.ratio p.value
 contrast     2 699   5.091  0.0064</code></pre>
</div>
</div>
<p>A joint <span class="math inline">\(F\)</span>-test, obtained by collapsing everything to a one-way ANOVA, shows that there are indeed differences. However, note that the averages of the three actions are much smaller than for race.</p>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Summary</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Complete factorial designs consist of experiments in which we manipulate multiple experimental factors at once and collect observations for each subgroup.</li>
<li>Factorial designs are more efficient than running repeatedly one-way analysis of variance with the same sample size per group.</li>
<li>Interactions occur when the effect of a variable depends on the levels of the others.</li>
<li>Interaction plots (group average per group) can help capture this difference, but beware of overinterpretation in small samples.</li>
<li>If there is an interaction, we consider differences and contrasts for each level of the other factor (<strong>simple effects</strong>).</li>
<li>If there is no interaction, we can pool observations and look at <strong>main effects</strong>.</li>
<li>A multiway analysis of variance can be treated as a one-way analysis of variance by collapsing categories; however, only specific contrasts will be of interest.</li>
<li>The number of observations increases quickly with the dimension as we increase the number of factors considered.</li>
</ul>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Crump.Navarro.Suzuki:2019" class="csl-entry" role="listitem">
Crump, M. J. C., D. J. Navarro, and J. Suzuki. 2019. <em>Answering Questions with Data: Introductory Statistics for Psychology Students</em>. <a href="https://doi.org/10.17605/OSF.IO/JZE52">https://doi.org/10.17605/OSF.IO/JZE52</a>.
</div>
<div id="ref-Lin.Kim.Uduehi.Keinan:2024" class="csl-entry" role="listitem">
Lin, Jason D, Nicole You Jeung Kim, Esther Uduehi, and Anat Keinan. 2024. <span>“Culture for Sale: Unpacking Consumer Perceptions of Cultural Appropriation.”</span> <em>Journal of Consumer Research</em>. <a href="https://doi.org/10.1093/jcr/ucad076">https://doi.org/10.1093/jcr/ucad076</a>.
</div>
<div id="ref-Maglio.Polman:2014" class="csl-entry" role="listitem">
Maglio, Sam J., and Evan Polman. 2014. <span>“Spatial Orientation Shrinks and Expands Psychological Distance.”</span> <em>Psychological Science</em> 25 (7): 1345–52. <a href="https://doi.org/10.1177/0956797614530571">https://doi.org/10.1177/0956797614530571</a>.
</div>
<div id="ref-Sharma.Tully.Cryder:2021" class="csl-entry" role="listitem">
Sharma, Eesha, Stephanie Tully, and Cynthia Cryder. 2021. <span>“Psychological Ownership of (Borrowed) Money.”</span> <em>Journal of Marketing Research</em> 58 (3): 497–514. <a href="https://doi.org/10.1177/0022243721993816">https://doi.org/10.1177/0022243721993816</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>By complete design, it is meant that we gather observations for each subcategory.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-contrasts_multipletesting.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Contrasts and multiple testing</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-blocking_ancova.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Designs to reduce the error</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>